/*
 * Copyright 2025 Toly Pochkin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.goquick.sqlitenow.gradle.dart

import dev.goquick.sqlitenow.gradle.database.MigrationInspector
import dev.goquick.sqlitenow.gradle.generator.data.DataStructCodeGenerator
import dev.goquick.sqlitenow.gradle.model.AnnotatedCreateTableStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedExecuteStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedSelectStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedStatement
import dev.goquick.sqlitenow.gradle.processing.AffectedTablesResolver
import dev.goquick.sqlitenow.gradle.processing.AnnotationConstants
import dev.goquick.sqlitenow.gradle.processing.DynamicFieldUtils
import dev.goquick.sqlitenow.gradle.sqlinspect.DeleteStatement
import dev.goquick.sqlitenow.gradle.sqlinspect.InsertStatement
import dev.goquick.sqlitenow.gradle.sqlinspect.SQLBatchInspector
import dev.goquick.sqlitenow.gradle.sqlinspect.SchemaInspector
import dev.goquick.sqlitenow.gradle.sqlinspect.UpdateStatement
import dev.goquick.sqlitenow.gradle.util.pascalize
import java.io.File

internal class DartCodeGenerator(
    private val databaseName: String,
    private val outputDir: File,
    private val schemaInspector: SchemaInspector,
    private val sqlBatchInspector: SQLBatchInspector,
    private val migrationInspector: MigrationInspector,
    private val dataStructCodeGenerator: DataStructCodeGenerator,
    private val oversqlite: Boolean,
) {
    private val context = dataStructCodeGenerator.generatorContext
    private val adapterRegistry = DartAdapterRegistry()
    private val fieldMapper = DartFieldMapper(context, adapterRegistry)
    private val affectedTablesResolver by lazy {
        AffectedTablesResolver.fromStatements(
            createTableStatements = context.createTableStatements,
            createViewStatements = context.createViewStatements,
        )
    }
    private val oversqliteEmitter = DartOversqliteEmitter(
        databaseName = databaseName,
        createTableStatements = context.createTableStatements,
        oversqlite = oversqlite,
    )
    private val migrationEmitter = DartMigrationEmitter(
        schemaInspector = schemaInspector,
        sqlBatchInspector = sqlBatchInspector,
        migrationInspector = migrationInspector,
    )

    fun generateCode() {
        oversqliteEmitter.validateFlag()
        outputDir.mkdirs()
        val file = outputDir.resolve("${databaseName.toSnakeCase()}.dart")
        val code = DartWriter().apply {
            line("// Generated by SQLiteNow. Do not modify this file manually.")
            if (usesUint8List()) {
                line("import 'dart:typed_data';")
                line()
            }
            line("import 'package:sqlitenow_runtime/sqlitenow_runtime.dart';")
            if (oversqlite) {
                line("import 'package:sqlitenow_oversqlite/sqlitenow_oversqlite.dart';")
            }
            line()
            adapterRegistry.collect(context)
            emitAdapters()
            emitResultModels()
            emitParameterModels()
            emitDatabaseFacade()
            emitNamespaces()
        }.toString()
        file.writeText(code)
    }

    private fun DartWriter.emitAdapters() {
        line("final class ${databaseName}Adapters {")
        indent {
            if (adapterRegistry.isEmpty()) {
                line("const ${databaseName}Adapters();")
            } else {
                line("const ${databaseName}Adapters({")
                indent {
                    adapterRegistry.values.forEach { adapter ->
                        line("required this.${adapter.encodeName},")
                        line("required this.${adapter.decodeName},")
                    }
                }
                line("});")
                line()
                adapterRegistry.values.forEach { adapter ->
                    line("final Object? Function(Object? value) ${adapter.encodeName};")
                    line("final Object? Function(Object? value) ${adapter.decodeName};")
                    line()
                }
            }
        }
        line("}")
        line()
    }

    private fun DartWriter.emitResultModels() {
        val emitted = mutableSetOf<String>()
        selectStatements().forEach { (namespace, statement) ->
            val className = resultClassName(namespace, statement)
            if (emitted.add(className)) {
                emitResultModel(className, fieldMapper.fields(statement))
            }
            val joinedClassName = joinedResultClassName(namespace, statement)
            if (statement.hasCollectionMapping() && emitted.add(joinedClassName)) {
                emitResultModel(joinedClassName, fieldMapper.physicalFields(statement))
            }
        }
        executeStatements()
            .filter { (_, statement) -> statement.hasReturningClause() }
            .forEach { (namespace, statement) ->
                val className = resultClassName(namespace, statement)
                if (emitted.add(className)) {
                    emitResultModel(className, fieldMapper.returningFields(statement))
                }
            }
    }

    private fun DartWriter.emitResultModel(
        className: String,
        fields: List<DartField>,
    ) {
        line("final class $className {")
        indent {
            line("const $className({")
            indent {
                fields.forEach { field ->
                    line("required this.${field.propertyName},")
                }
            }
            line("});")
            line()
            fields.forEach { field ->
                line("final ${field.dartType} ${field.propertyName};")
            }
        }
        line("}")
        line()
    }

    private fun DartWriter.emitParameterModels() {
        statements().forEach { (namespace, statement) ->
            val params = parameterDescriptors(statement, unique = true)
            if (params.isEmpty()) return@forEach
            val className = paramsClassName(namespace, statement)
            line("final class $className {")
            indent {
                line("const $className({")
                indent {
                    params.forEach { param ->
                        line("required this.${param.propertyName},")
                    }
                }
                line("});")
                line()
                params.forEach { param ->
                    line("final ${param.dartType} ${param.propertyName};")
                }
            }
            line("}")
            line()
        }
    }

    private fun DartWriter.emitDatabaseFacade() {
            line("final class $databaseName {")
            indent {
                line("$databaseName.inMemory({")
                indent {
                    line(adapterRegistry.constructorParameter(databaseName))
                }
                line("}) : this._(")
            indent {
                line("SqliteNowDatabase.inMemory(migrations: _migrations),")
                line("adapters,")
            }
            line(");")
            line()
            line("$databaseName({")
            indent {
                line("required String path,")
                line(adapterRegistry.constructorParameter(databaseName))
            }
            line("}) : this._(")
            indent {
                line("SqliteNowDatabase(path: path, migrations: _migrations),")
                line("adapters,")
            }
            line(");")
            line()
            line("$databaseName._(this._database, this.adapters) {")
            indent {
                namespaces().forEach { namespace ->
                    line("${namespace.toLowerCamel()} = ${pascalize(namespace)}Queries(this);")
                }
            }
            line("}")
            line()
            line("final SqliteNowDatabase _database;")
            line("final ${databaseName}Adapters adapters;")
            namespaces().forEach { namespace ->
                line("late final ${pascalize(namespace)}Queries ${namespace.toLowerCamel()};")
            }
            line()
            line("bool get isOpen => _database.isOpen;")
            line("SqliteNowConnection get connection => _database.connection;")
            line("Future<void> open() => _database.open();")
            line("Future<void> close() => _database.close();")
            line("Future<T> transaction<T>(Future<T> Function() block, {TransactionMode mode = TransactionMode.deferred}) {")
            indent {
                line("return _database.transaction(block, mode: mode);")
            }
            line("}")
            line("void reportExternalTableChanges(Set<String> affectedTables) {")
            indent {
                line("_database.reportExternalTableChanges(affectedTables);")
            }
            line("}")
            line("SqliteNowDatabase get runtimeDatabase => _database;")
            line()
            oversqliteEmitter.emit(this)
            migrationEmitter.emit(this)
        }
        line("}")
        line()
    }

    private fun DartWriter.emitNamespaces() {
        namespaces().forEach { namespace ->
            line("final class ${pascalize(namespace)}Queries {")
            indent {
                line("${pascalize(namespace)}Queries(this._db);")
                line()
                line("final $databaseName _db;")
                line()
                context.nsWithStatements[namespace].orEmpty().forEach { statement ->
                    when (statement) {
                        is AnnotatedSelectStatement -> emitSelectFunction(namespace, statement)
                        is AnnotatedExecuteStatement -> emitExecuteFunction(namespace, statement)
                        else -> Unit
                    }
                    line()
                }
            }
            line("}")
            line()
        }
    }

    private fun DartWriter.emitSelectFunction(namespace: String, statement: AnnotatedSelectStatement) {
        val functionName = statement.name.toLowerCamel()
        val params = parameterDescriptors(statement, unique = false)
        val paramsClass = paramsClassName(namespace, statement)
        val resultClass = resultClassName(namespace, statement)
        val affectedTables = affectedTablesResolver.tablesFor(statement)
        if (params.isEmpty()) {
            line("SelectRunner<$resultClass> $functionName() {")
        } else {
            line("SelectRunner<$resultClass> $functionName($paramsClass params) {")
        }
        indent {
            line("return SelectRunner<$resultClass>(")
            indent {
                line("database: _db.runtimeDatabase,")
                line("affectedTables: ${affectedTables.toDartSetLiteral()},")
                if (statement.hasCollectionMapping()) {
                    emitCollectionQueryBody(namespace, statement, params, resultClass)
                } else {
                    line("query: () {")
                    indent {
                        line("return _db.connection.select(")
                        indent {
                            line("${statement.src.sql.toDartRawString()},")
                            line("(row) => ${readResultExpression(resultClass, statement, fieldMapper.fields(statement), "row")},")
                            if (params.isNotEmpty()) {
                                line("parameters: ${parameterListExpression(params)},")
                            }
                        }
                        line(");")
                    }
                    line("},")
                }
            }
            line(");")
        }
        line("}")
    }

    private fun DartWriter.emitCollectionQueryBody(
        namespace: String,
        statement: AnnotatedSelectStatement,
        params: List<DartParameter>,
        resultClass: String,
    ) {
        val joinedClass = joinedResultClassName(namespace, statement)
        val collectionKey = statement.annotations.collectionKey
            ?: error("Collection-mapped Dart SELECT '${statement.name}' is missing statement-level collectionKey.")
        val groupKeyField = fieldMapper.physicalFields(statement).firstOrNull { it.source?.src?.fieldName == collectionKey }
            ?: error("Collection key '$collectionKey' was not selected by Dart SELECT '${statement.name}'.")

        line("query: () async {")
        indent {
            line("final joinedRows = await _db.connection.select(")
            indent {
                line("${statement.src.sql.toDartRawString()},")
                line("(row) => ${readResultExpression(joinedClass, statement, fieldMapper.physicalFields(statement), "row")},")
                if (params.isNotEmpty()) {
                    line("parameters: ${parameterListExpression(params)},")
                }
            }
            line(");")
            line("final groupedRows = <Object?, List<$joinedClass>>{};")
            line("for (final joinedRow in joinedRows) {")
            indent {
                line("groupedRows.putIfAbsent(joinedRow.${groupKeyField.propertyName}, () => <$joinedClass>[]).add(joinedRow);")
            }
            line("}")
            line("final resultRows = <$resultClass>[];")
            line("for (final rowsForEntity in groupedRows.values) {")
            indent {
                line("final first = rowsForEntity.first;")
                statement.mappingPlan.includedCollectionFields.forEach { dynamicField ->
                    val collectionProperty = fieldMapper.dynamicFieldPropertyName(dynamicField)
                    val collectionType = dynamicField.annotations.propertyType
                        ?: error("Collection dynamic field '${dynamicField.src.fieldName}' is missing propertyType.")
                    val elementType = collectionType.collectionElementType()
                    val collectionKeyColumn = dynamicField.annotations.collectionKey
                        ?: error("Collection dynamic field '${dynamicField.src.fieldName}' is missing collectionKey.")
                    val collectionKeyField = fieldMapper.physicalFields(statement)
                        .firstOrNull { it.source?.src?.fieldName == collectionKeyColumn }
                        ?: error("Collection key '$collectionKeyColumn' was not selected by Dart SELECT '${statement.name}'.")
                    line("final ${collectionProperty}Seen = <Object?>{};")
                    line("final $collectionProperty = <$elementType>[];")
                    line("for (final joinedRow in rowsForEntity) {")
                    indent {
                        line("final key = joinedRow.${collectionKeyField.propertyName};")
                        line("if (key == null || !${collectionProperty}Seen.add(key)) {")
                        indent {
                            line("continue;")
                        }
                        line("}")
                        line("$collectionProperty.add(${dynamicObjectExpression(statement, dynamicField, "joinedRow", fromJoinedRow = true)});")
                    }
                    line("}")
                }
                line("resultRows.add(")
                indent {
                    line("${readResultExpression(resultClass, statement, fieldMapper.fields(statement), "first", fromJoinedRow = true)},")
                }
                line(");")
            }
            line("}")
            line("return resultRows;")
        }
        line("},")
    }

    private fun DartWriter.emitExecuteFunction(namespace: String, statement: AnnotatedExecuteStatement) {
        val functionName = statement.name.toLowerCamel()
        val params = parameterDescriptors(statement, unique = false)
        val paramsClass = paramsClassName(namespace, statement)
        val affectedTables = affectedTablesResolver.tablesFor(statement)
        val signatureParams = if (params.isEmpty()) "" else "$paramsClass params"
        if (statement.hasReturningClause()) {
            val resultClass = resultClassName(namespace, statement)
            line("Future<List<$resultClass>> $functionName($signatureParams) async {")
            indent {
                line("final rows = await _db.connection.usePrepared(")
                indent {
                    line("${statement.src.sql.toDartRawString()},")
                    line("(statement) {")
                    indent {
                        line("return statement.select(")
                        indent {
                            line("(row) => ${readResultExpression(resultClass, null, fieldMapper.returningFields(statement), "row")},")
                            if (params.isEmpty()) {
                                line("const [],")
                            } else {
                                line("${parameterListExpression(params)},")
                            }
                        }
                        line(");")
                    }
                    line("},")
                }
                line(");")
                line("_db.reportExternalTableChanges(${affectedTables.toDartSetLiteral()});")
                line("return rows;")
            }
            line("}")
            line()
            line("Future<$resultClass> ${functionName}One($signatureParams) async {")
            indent {
                line("final rows = await $functionName(${params.forwardingArgument()});")
                line("if (rows.length != 1) {")
                indent {
                    line("throw StateError('Expected exactly one row, got \${rows.length}');")
                }
                line("}")
                line("return rows.single;")
            }
            line("}")
            line()
            line("Future<$resultClass?> ${functionName}OneOrNull($signatureParams) async {")
            indent {
                line("final rows = await $functionName(${params.forwardingArgument()});")
                line("if (rows.length > 1) {")
                indent {
                    line("throw StateError('Expected zero or one row, got \${rows.length}');")
                }
                line("}")
                line("return rows.isEmpty ? null : rows.single;")
            }
            line("}")
        } else {
            line("Future<void> $functionName($signatureParams) async {")
            indent {
                line("await _db.connection.execute(")
                indent {
                    line("${statement.src.sql.toDartRawString()},")
                    if (params.isNotEmpty()) {
                        line("parameters: ${parameterListExpression(params)},")
                    }
                    line("affectedTables: ${affectedTables.toDartSetLiteral()},")
                }
                line(");")
            }
            line("}")
        }
    }

    private fun readResultExpression(
        resultClass: String,
        statement: AnnotatedSelectStatement?,
        fields: List<DartField>,
        rowVar: String,
        fromJoinedRow: Boolean = false,
    ): String {
        return buildString {
            append("$resultClass(")
            fields.forEach { field ->
                append("${field.propertyName}: ${readFieldExpression(statement, field, rowVar, fromJoinedRow)}, ")
            }
            append(")")
        }
    }

    private fun readFieldExpression(
        statement: AnnotatedSelectStatement?,
        field: DartField,
        rowVar: String,
        fromJoinedRow: Boolean,
    ): String {
        field.dynamicField?.let { dynamicField ->
            if (dynamicField.annotations.mappingType == AnnotationConstants.MAPPING_TYPE_COLLECTION) {
                return field.propertyName
            }
            check(statement != null) { "Dynamic Dart field '${field.propertyName}' requires SELECT statement context." }
            return dynamicObjectExpression(statement, dynamicField, rowVar, fromJoinedRow)
        }
        if (fromJoinedRow) {
            return "$rowVar.${field.propertyName}"
        }
        val readCall = "$rowVar.${field.sqliteReadCall}(${field.index})"
        val adapter = field.adapter
        if (adapter == null) return readCall
        val decoded = "_db.adapters.${adapter.decodeName}($readCall)"
        return if (field.nullable) {
            "$decoded as ${field.dartType}"
        } else {
            "$decoded as ${field.dartType}"
        }
    }

    private fun dynamicObjectExpression(
        statement: AnnotatedSelectStatement,
        dynamicField: AnnotatedSelectStatement.Field,
        rowVar: String,
        fromJoinedRow: Boolean,
    ): String {
        val mapping = statement.mappingPlan.dynamicMappingsByField[dynamicField.src.fieldName]
            ?: error("Dynamic field '${dynamicField.src.fieldName}' has no mapping columns.")
        val columns = mapping.columns
            .filterNot { column -> DynamicFieldUtils.isNestedAlias(column.fieldName, dynamicField.annotations.aliasPrefix) }
            .map { column -> fieldMapper.mappingColumn(statement, dynamicField, column) }
        val mappingType = AnnotationConstants.MappingType.fromString(dynamicField.annotations.mappingType)
        val rawPropertyType = dynamicField.annotations.propertyType
            ?: error("Dynamic field '${dynamicField.src.fieldName}' is missing propertyType.")
        val propertyType = rawPropertyType.toDartTypeName().removeSuffix("?")
        val className = if (mappingType == AnnotationConstants.MappingType.COLLECTION) {
            rawPropertyType.collectionElementType()
        } else {
            propertyType
        }
        val constructor = buildString {
            append("$className(")
            columns.forEach { column ->
                val value = if (fromJoinedRow) {
                    "$rowVar.${column.sourcePropertyName}${if (column.field.nullable) "" else "!"}"
                } else {
                    readFieldExpression(null, column.field, rowVar, fromJoinedRow = false)
                }
                append("${column.constructorPropertyName}: $value, ")
            }
            append(")")
        }
        val nullable = dynamicField.annotations.notNull != true &&
            mappingType != AnnotationConstants.MappingType.ENTITY
        if (!nullable) return constructor
        val nullCheck = columns.joinToString(" && ") { column ->
            if (fromJoinedRow) {
                "$rowVar.${column.sourcePropertyName} == null"
            } else {
                "$rowVar.readValue(${column.field.index}) == null"
            }
        }
        return "($nullCheck ? null : $constructor)"
    }

    private fun parameterListExpression(params: List<DartParameter>): String {
        return buildString {
            append("[")
            params.forEach { param ->
                val rawValue = "params.${param.propertyName}"
                val value = when {
                    param.adapter == null -> rawValue
                    param.dartType.removeSuffix("?").startsWith("List<") -> {
                        val mapped = "$rawValue.map((value) => _db.adapters.${param.adapter.encodeName}(value)).toList()"
                        if (param.dartType.endsWith("?")) {
                            "$rawValue?.map((value) => _db.adapters.${param.adapter.encodeName}(value)).toList()"
                        } else {
                            mapped
                        }
                    }

                    else -> "_db.adapters.${param.adapter.encodeName}($rawValue)"
                }
                append("$value, ")
            }
            append("]")
        }
    }

    private fun parameterDescriptors(statement: AnnotatedStatement, unique: Boolean): List<DartParameter> {
        val names = if (unique) {
            statement.srcNamedParameters().distinct()
        } else {
            statement.srcNamedParameters()
        }
        return names.map { name ->
            val propertyName = statement.annotations.propertyNameGenerator.convertToPropertyName(name)
            val type = dataStructCodeGenerator.inferParameterType(name, statement).toDartType()
            val column = parameterColumn(statement, name)
            DartParameter(
                propertyName = propertyName,
                dartType = type,
                adapter = column?.let { adapterRegistry.adapterFor(it.first.src.tableName, it.second.src.name, it.second) },
            )
        }
    }

    private fun parameterColumn(
        statement: AnnotatedStatement,
        parameterName: String,
    ): Pair<AnnotatedCreateTableStatement, AnnotatedCreateTableStatement.Column>? {
        val tableAndColumn = when (statement) {
            is AnnotatedExecuteStatement -> when (val src = statement.src) {
                is InsertStatement -> src.table to src.columnNamesAssociatedWithNamedParameters[parameterName]
                is UpdateStatement -> src.table to src.namedParametersToColumnNames[parameterName]
                is DeleteStatement -> src.table to null
            }

            is AnnotatedSelectStatement -> {
                val column = context.columnLookup.findColumnForParameter(statement, parameterName)
                    ?: return null
                return context.createTableStatements
                    .firstOrNull { it.findColumnByName(column.src.name) === column }
                    ?.let { it to column }
            }

            else -> return null
        }
        val tableName = tableAndColumn.first
        val columnName = tableAndColumn.second ?: return null
        val table = context.createTableStatements.firstOrNull {
            it.src.tableName.equals(tableName, ignoreCase = true)
        } ?: return null
        val column = table.findColumnByName(columnName) ?: return null
        return table to column
    }

    private fun selectStatements(): List<Pair<String, AnnotatedSelectStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.filterIsInstance<AnnotatedSelectStatement>().map { namespace to it }
        }

    private fun executeStatements(): List<Pair<String, AnnotatedExecuteStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.filterIsInstance<AnnotatedExecuteStatement>().map { namespace to it }
        }

    private fun statements(): List<Pair<String, AnnotatedStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.mapNotNull { statement ->
                when (statement) {
                    is AnnotatedSelectStatement,
                    is AnnotatedExecuteStatement -> namespace to statement

                    else -> null
                }
            }
        }

    private fun namespaces(): List<String> = context.nsWithStatements.keys.sorted()

    private fun usesUint8List(): Boolean {
        return fieldMapper.usesUint8List(selectStatements(), executeStatements())
    }

    private fun resultClassName(namespace: String, statement: AnnotatedStatement): String =
        statement.annotations.queryResult ?: defaultClassName(namespace, statement, "Result")

    private fun joinedResultClassName(namespace: String, statement: AnnotatedSelectStatement): String =
        "_${resultClassName(namespace, statement)}JoinedRow"

    private fun paramsClassName(namespace: String, statement: AnnotatedStatement): String =
        defaultClassName(namespace, statement, "Params")

    private fun defaultClassName(namespace: String, statement: AnnotatedStatement, suffix: String): String =
        "${pascalize(namespace)}${statement.getDataClassName()}$suffix"

    private fun AnnotatedStatement.srcNamedParameters(): List<String> =
        when (this) {
            is AnnotatedSelectStatement -> src.namedParameters
            is AnnotatedExecuteStatement -> src.namedParameters
            else -> emptyList()
        }
}
