/*
 * Copyright 2025 Toly Pochkin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.goquick.sqlitenow.gradle.dart

import com.squareup.kotlinpoet.TypeName
import dev.goquick.sqlitenow.gradle.database.MigrationInspector
import dev.goquick.sqlitenow.gradle.generator.data.DataStructCodeGenerator
import dev.goquick.sqlitenow.gradle.model.AnnotatedCreateTableStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedExecuteStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedSelectStatement
import dev.goquick.sqlitenow.gradle.model.AnnotatedStatement
import dev.goquick.sqlitenow.gradle.oversqlite.resolveOversqliteSyncTables
import dev.goquick.sqlitenow.gradle.processing.AnnotationConstants
import dev.goquick.sqlitenow.gradle.processing.DynamicFieldUtils
import dev.goquick.sqlitenow.gradle.processing.FieldAnnotationOverrides
import dev.goquick.sqlitenow.gradle.processing.StatementAnnotationOverrides
import dev.goquick.sqlitenow.gradle.sqlinspect.DeleteStatement
import dev.goquick.sqlitenow.gradle.sqlinspect.InsertStatement
import dev.goquick.sqlitenow.gradle.sqlinspect.SQLBatchInspector
import dev.goquick.sqlitenow.gradle.sqlinspect.SchemaInspector
import dev.goquick.sqlitenow.gradle.sqlinspect.SelectStatement
import dev.goquick.sqlitenow.gradle.sqlinspect.UpdateStatement
import dev.goquick.sqlitenow.gradle.util.pascalize
import java.io.File
import java.util.Locale

internal class DartCodeGenerator(
    private val databaseName: String,
    private val outputDir: File,
    private val schemaInspector: SchemaInspector,
    private val sqlBatchInspector: SQLBatchInspector,
    private val migrationInspector: MigrationInspector,
    private val dataStructCodeGenerator: DataStructCodeGenerator,
    private val oversqlite: Boolean,
) {
    private val context = dataStructCodeGenerator.generatorContext
    private val adapterColumns = linkedMapOf<String, DartAdapterColumn>()
    private val createViewStatementsByName by lazy {
        context.createViewStatements.associateBy { it.src.viewName.lowercase(Locale.ROOT) }
    }
    private val viewTableDependencies by lazy {
        context.createViewStatements.associate { view ->
            val key = view.src.viewName.lowercase(Locale.ROOT)
            key to resolveViewDependencies(key, mutableSetOf())
        }
    }
    private val cascadeNotifyByTable by lazy {
        context.createTableStatements.mapNotNull { table ->
            val cascade = table.annotations.cascadeNotify ?: return@mapNotNull null
            table.src.tableName.lowercase(Locale.ROOT) to cascade
        }.toMap()
    }
    private val cascadeClosureCache =
        mutableMapOf<Pair<String, StatementAnnotationOverrides.CascadeAction>, Set<String>>()
    private val resolvedSyncTables by lazy {
        resolveOversqliteSyncTables(
            databaseClassName = databaseName,
            createTableStatements = context.createTableStatements,
            oversqlite = oversqlite,
        )
    }

    fun generateCode() {
        validateOversqliteFlag()
        outputDir.mkdirs()
        val file = outputDir.resolve("${databaseName.toSnakeCase()}.dart")
        val code = DartWriter().apply {
            line("// Generated by SQLiteNow. Do not modify this file manually.")
            if (usesUint8List()) {
                line("import 'dart:typed_data';")
                line()
            }
            line("import 'package:sqlitenow_runtime/sqlitenow_runtime.dart';")
            if (oversqlite) {
                line("import 'package:sqlitenow_oversqlite/sqlitenow_oversqlite.dart';")
            }
            line()
            collectAdapters()
            emitAdapters()
            emitResultModels()
            emitParameterModels()
            emitDatabaseFacade()
            emitNamespaces()
        }.toString()
        file.writeText(code)
    }

    private fun DartWriter.emitAdapters() {
        line("final class ${databaseName}Adapters {")
        indent {
            if (adapterColumns.isEmpty()) {
                line("const ${databaseName}Adapters();")
            } else {
                line("const ${databaseName}Adapters({")
                indent {
                    adapterColumns.values.forEach { adapter ->
                        line("required this.${adapter.encodeName},")
                        line("required this.${adapter.decodeName},")
                    }
                }
                line("});")
                line()
                adapterColumns.values.forEach { adapter ->
                    line("final Object? Function(Object? value) ${adapter.encodeName};")
                    line("final Object? Function(Object? value) ${adapter.decodeName};")
                    line()
                }
            }
        }
        line("}")
        line()
    }

    private fun DartWriter.emitResultModels() {
        val emitted = mutableSetOf<String>()
        selectStatements().forEach { (namespace, statement) ->
            val className = selectResultClassName(namespace, statement)
            if (emitted.add(className)) {
                emitResultModel(className, statement.fields())
            }
            val joinedClassName = joinedResultClassName(namespace, statement)
            if (statement.hasCollectionMapping() && emitted.add(joinedClassName)) {
                emitResultModel(joinedClassName, statement.physicalFields())
            }
        }
        executeStatements()
            .filter { (_, statement) -> statement.hasReturningClause() }
            .forEach { (namespace, statement) ->
                val className = returningResultClassName(namespace, statement)
                if (emitted.add(className)) {
                    emitResultModel(className, returningFields(statement))
                }
            }
    }

    private fun DartWriter.emitResultModel(
        className: String,
        fields: List<DartField>,
    ) {
        line("final class $className {")
        indent {
            line("const $className({")
            indent {
                fields.forEach { field ->
                    line("required this.${field.propertyName},")
                }
            }
            line("});")
            line()
            fields.forEach { field ->
                line("final ${field.dartType} ${field.propertyName};")
            }
        }
        line("}")
        line()
    }

    private fun DartWriter.emitParameterModels() {
        statements().forEach { (namespace, statement) ->
            val params = parameterDescriptors(statement, unique = true)
            if (params.isEmpty()) return@forEach
            val className = paramsClassName(namespace, statement)
            line("final class $className {")
            indent {
                line("const $className({")
                indent {
                    params.forEach { param ->
                        line("required this.${param.propertyName},")
                    }
                }
                line("});")
                line()
                params.forEach { param ->
                    line("final ${param.dartType} ${param.propertyName};")
                }
            }
            line("}")
            line()
        }
    }

    private fun DartWriter.emitDatabaseFacade() {
        line("final class $databaseName {")
        indent {
            line("$databaseName.inMemory({")
            indent {
                line(adapterConstructorParameter())
            }
            line("}) : this._(")
            indent {
                line("SqliteNowDatabase.inMemory(migrations: _migrations),")
                line("adapters,")
            }
            line(");")
            line()
            line("$databaseName({")
            indent {
                line("required String path,")
                line(adapterConstructorParameter())
            }
            line("}) : this._(")
            indent {
                line("SqliteNowDatabase(path: path, migrations: _migrations),")
                line("adapters,")
            }
            line(");")
            line()
            line("$databaseName._(this._database, this.adapters) {")
            indent {
                namespaces().forEach { namespace ->
                    line("${namespace.toLowerCamel()} = ${pascalize(namespace)}Queries(this);")
                }
            }
            line("}")
            line()
            line("final SqliteNowDatabase _database;")
            line("final ${databaseName}Adapters adapters;")
            namespaces().forEach { namespace ->
                line("late final ${pascalize(namespace)}Queries ${namespace.toLowerCamel()};")
            }
            line()
            line("bool get isOpen => _database.isOpen;")
            line("SqliteNowConnection get connection => _database.connection;")
            line("Future<void> open() => _database.open();")
            line("Future<void> close() => _database.close();")
            line("Future<T> transaction<T>(Future<T> Function() block, {TransactionMode mode = TransactionMode.deferred}) {")
            indent {
                line("return _database.transaction(block, mode: mode);")
            }
            line("}")
            line("void reportExternalTableChanges(Set<String> affectedTables) {")
            indent {
                line("_database.reportExternalTableChanges(affectedTables);")
            }
            line("}")
            line("SqliteNowDatabase get runtimeDatabase => _database;")
            line()
            emitOversqliteMetadata()
            emitMigrations()
        }
        line("}")
        line()
    }

    private fun DartWriter.emitOversqliteMetadata() {
        if (!oversqlite) return

        line("static const List<SyncTable> syncTables = <SyncTable>[")
        indent {
            resolvedSyncTables.forEach { syncTable ->
                line(
                    "SyncTable(tableName: '${syncTable.table.name}', " +
                        "syncKeyColumnName: '${syncTable.syncKeyColumnName}'),"
                )
            }
        }
        line("];")
        line()
        line("OversqliteConfig buildOversqliteConfig({")
        indent {
            line("required String schema,")
            line("int uploadLimit = 200,")
            line("int downloadLimit = 1000,")
            line("bool verboseLogs = false,")
        }
        line("}) {")
        indent {
            line("return OversqliteConfig(")
            indent {
                line("schema: schema,")
                line("syncTables: syncTables,")
                line("uploadLimit: uploadLimit,")
                line("downloadLimit: downloadLimit,")
                line("verboseLogs: verboseLogs,")
            }
            line(");")
        }
        line("}")
        line()
        line("DefaultOversqliteClient newOversqliteClient({")
        indent {
            line("required String schema,")
            line("required OversqliteHttpClient httpClient,")
            line("int uploadLimit = 200,")
            line("int downloadLimit = 1000,")
            line("bool verboseLogs = false,")
        }
        line("}) {")
        indent {
            line("final config = buildOversqliteConfig(")
            indent {
                line("schema: schema,")
                line("uploadLimit: uploadLimit,")
                line("downloadLimit: downloadLimit,")
                line("verboseLogs: verboseLogs,")
            }
            line(");")
            line("return DefaultOversqliteClient(")
            indent {
                line("database: _database,")
                line("config: config,")
                line("httpClient: httpClient,")
            }
            line(");")
        }
        line("}")
        line()
    }

    private fun validateOversqliteFlag() {
        if (!oversqlite && resolvedSyncTables.isNotEmpty()) {
            error(
                "Dart database '$databaseName' has tables annotated with enableSync=true, but oversqlite=false. " +
                    "Set oversqlite=true for Dart Oversqlite metadata generation or remove enableSync=true."
            )
        }
    }

    private fun DartWriter.emitMigrations() {
        line("static final List<SqliteNowMigrationStep> _migrations = [")
        indent {
            migrationSteps().forEach { step ->
                if (step.freshOnly) {
                    line("SqliteNowMigrationStep.fresh(${step.version}, (connection) async {")
                } else {
                    line("SqliteNowMigrationStep(${step.version}, (connection) async {")
                }
                indent {
                    step.statements.forEach { statement ->
                        line("await connection.execute(${statement.toDartRawString()});")
                    }
                }
                line("}),")
            }
        }
        line("];")
    }

    private fun DartWriter.emitNamespaces() {
        namespaces().forEach { namespace ->
            line("final class ${pascalize(namespace)}Queries {")
            indent {
                line("${pascalize(namespace)}Queries(this._db);")
                line()
                line("final $databaseName _db;")
                line()
                context.nsWithStatements[namespace].orEmpty().forEach { statement ->
                    when (statement) {
                        is AnnotatedSelectStatement -> emitSelectFunction(namespace, statement)
                        is AnnotatedExecuteStatement -> emitExecuteFunction(namespace, statement)
                        else -> Unit
                    }
                    line()
                }
            }
            line("}")
            line()
        }
    }

    private fun DartWriter.emitSelectFunction(namespace: String, statement: AnnotatedSelectStatement) {
        val functionName = statement.name.toLowerCamel()
        val params = parameterDescriptors(statement, unique = false)
        val paramsClass = paramsClassName(namespace, statement)
        val resultClass = selectResultClassName(namespace, statement)
        val affectedTables = affectedTables(statement)
        if (params.isEmpty()) {
            line("SelectRunner<$resultClass> $functionName() {")
        } else {
            line("SelectRunner<$resultClass> $functionName($paramsClass params) {")
        }
        indent {
            line("return SelectRunner<$resultClass>(")
            indent {
                line("database: _db.runtimeDatabase,")
                line("affectedTables: ${affectedTables.toDartSetLiteral()},")
                if (statement.hasCollectionMapping()) {
                    emitCollectionQueryBody(namespace, statement, params, resultClass)
                } else {
                    line("query: () {")
                    indent {
                        line("return _db.connection.select(")
                        indent {
                            line("${statement.src.sql.toDartRawString()},")
                            line("(row) => ${readResultExpression(resultClass, statement, statement.fields(), "row")},")
                            if (params.isNotEmpty()) {
                                line("parameters: ${parameterListExpression(params)},")
                            }
                        }
                        line(");")
                    }
                    line("},")
                }
            }
            line(");")
        }
        line("}")
    }

    private fun DartWriter.emitCollectionQueryBody(
        namespace: String,
        statement: AnnotatedSelectStatement,
        params: List<DartParameter>,
        resultClass: String,
    ) {
        val joinedClass = joinedResultClassName(namespace, statement)
        val collectionKey = statement.annotations.collectionKey
            ?: error("Collection-mapped Dart SELECT '${statement.name}' is missing statement-level collectionKey.")
        val groupKeyField = statement.physicalFields().firstOrNull { it.source?.src?.fieldName == collectionKey }
            ?: error("Collection key '$collectionKey' was not selected by Dart SELECT '${statement.name}'.")

        line("query: () async {")
        indent {
            line("final joinedRows = await _db.connection.select(")
            indent {
                line("${statement.src.sql.toDartRawString()},")
                line("(row) => ${readResultExpression(joinedClass, statement, statement.physicalFields(), "row")},")
                if (params.isNotEmpty()) {
                    line("parameters: ${parameterListExpression(params)},")
                }
            }
            line(");")
            line("final groupedRows = <Object?, List<$joinedClass>>{};")
            line("for (final joinedRow in joinedRows) {")
            indent {
                line("groupedRows.putIfAbsent(joinedRow.${groupKeyField.propertyName}, () => <$joinedClass>[]).add(joinedRow);")
            }
            line("}")
            line("final resultRows = <$resultClass>[];")
            line("for (final rowsForEntity in groupedRows.values) {")
            indent {
                line("final first = rowsForEntity.first;")
                statement.mappingPlan.includedCollectionFields.forEach { dynamicField ->
                    val collectionProperty = dynamicFieldPropertyName(dynamicField)
                    val collectionType = dynamicField.annotations.propertyType
                        ?: error("Collection dynamic field '${dynamicField.src.fieldName}' is missing propertyType.")
                    val elementType = collectionType.collectionElementType()
                    val collectionKeyColumn = dynamicField.annotations.collectionKey
                        ?: error("Collection dynamic field '${dynamicField.src.fieldName}' is missing collectionKey.")
                    val collectionKeyField = statement.physicalFields()
                        .firstOrNull { it.source?.src?.fieldName == collectionKeyColumn }
                        ?: error("Collection key '$collectionKeyColumn' was not selected by Dart SELECT '${statement.name}'.")
                    line("final ${collectionProperty}Seen = <Object?>{};")
                    line("final $collectionProperty = <$elementType>[];")
                    line("for (final joinedRow in rowsForEntity) {")
                    indent {
                        line("final key = joinedRow.${collectionKeyField.propertyName};")
                        line("if (key == null || !${collectionProperty}Seen.add(key)) {")
                        indent {
                            line("continue;")
                        }
                        line("}")
                        line("$collectionProperty.add(${dynamicObjectExpression(statement, dynamicField, "joinedRow", fromJoinedRow = true)});")
                    }
                    line("}")
                }
                line("resultRows.add(")
                indent {
                    line("${readResultExpression(resultClass, statement, statement.fields(), "first", fromJoinedRow = true)},")
                }
                line(");")
            }
            line("}")
            line("return resultRows;")
        }
        line("},")
    }

    private fun DartWriter.emitExecuteFunction(namespace: String, statement: AnnotatedExecuteStatement) {
        val functionName = statement.name.toLowerCamel()
        val params = parameterDescriptors(statement, unique = false)
        val paramsClass = paramsClassName(namespace, statement)
        val affectedTables = affectedTables(statement)
        val signatureParams = if (params.isEmpty()) "" else "$paramsClass params"
        if (statement.hasReturningClause()) {
            val resultClass = returningResultClassName(namespace, statement)
            line("Future<List<$resultClass>> $functionName($signatureParams) async {")
            indent {
                line("final rows = await _db.connection.usePrepared(")
                indent {
                    line("${statement.src.sql.toDartRawString()},")
                    line("(statement) {")
                    indent {
                        line("return statement.select(")
                        indent {
                            line("(row) => ${readResultExpression(resultClass, null, returningFields(statement), "row")},")
                            if (params.isEmpty()) {
                                line("const [],")
                            } else {
                                line("${parameterListExpression(params)},")
                            }
                        }
                        line(");")
                    }
                    line("},")
                }
                line(");")
                line("_db.reportExternalTableChanges(${affectedTables.toDartSetLiteral()});")
                line("return rows;")
            }
            line("}")
            line()
            line("Future<$resultClass> ${functionName}One($signatureParams) async {")
            indent {
                line("final rows = await $functionName(${params.forwardingArgument()});")
                line("if (rows.length != 1) {")
                indent {
                    line("throw StateError('Expected exactly one row, got \${rows.length}');")
                }
                line("}")
                line("return rows.single;")
            }
            line("}")
            line()
            line("Future<$resultClass?> ${functionName}OneOrNull($signatureParams) async {")
            indent {
                line("final rows = await $functionName(${params.forwardingArgument()});")
                line("if (rows.length > 1) {")
                indent {
                    line("throw StateError('Expected zero or one row, got \${rows.length}');")
                }
                line("}")
                line("return rows.isEmpty ? null : rows.single;")
            }
            line("}")
        } else {
            line("Future<void> $functionName($signatureParams) async {")
            indent {
                line("await _db.connection.execute(")
                indent {
                    line("${statement.src.sql.toDartRawString()},")
                    if (params.isNotEmpty()) {
                        line("parameters: ${parameterListExpression(params)},")
                    }
                    line("affectedTables: ${affectedTables.toDartSetLiteral()},")
                }
                line(");")
            }
            line("}")
        }
    }

    private fun readResultExpression(
        resultClass: String,
        statement: AnnotatedSelectStatement?,
        fields: List<DartField>,
        rowVar: String,
        fromJoinedRow: Boolean = false,
    ): String {
        return buildString {
            append("$resultClass(")
            fields.forEach { field ->
                append("${field.propertyName}: ${readFieldExpression(statement, field, rowVar, fromJoinedRow)}, ")
            }
            append(")")
        }
    }

    private fun readFieldExpression(
        statement: AnnotatedSelectStatement?,
        field: DartField,
        rowVar: String,
        fromJoinedRow: Boolean,
    ): String {
        field.dynamicField?.let { dynamicField ->
            if (dynamicField.annotations.mappingType == AnnotationConstants.MAPPING_TYPE_COLLECTION) {
                return field.propertyName
            }
            check(statement != null) { "Dynamic Dart field '${field.propertyName}' requires SELECT statement context." }
            return dynamicObjectExpression(statement, dynamicField, rowVar, fromJoinedRow)
        }
        if (fromJoinedRow) {
            return "$rowVar.${field.propertyName}"
        }
        val readCall = "$rowVar.${field.sqliteReadCall}(${field.index})"
        val adapter = field.adapter
        if (adapter == null) return readCall
        val decoded = "_db.adapters.${adapter.decodeName}($readCall)"
        return if (field.nullable) {
            "$decoded as ${field.dartType}"
        } else {
            "$decoded as ${field.dartType}"
        }
    }

    private fun dynamicObjectExpression(
        statement: AnnotatedSelectStatement,
        dynamicField: AnnotatedSelectStatement.Field,
        rowVar: String,
        fromJoinedRow: Boolean,
    ): String {
        val mapping = statement.mappingPlan.dynamicMappingsByField[dynamicField.src.fieldName]
            ?: error("Dynamic field '${dynamicField.src.fieldName}' has no mapping columns.")
        val columns = mapping.columns
            .filterNot { column -> DynamicFieldUtils.isNestedAlias(column.fieldName, dynamicField.annotations.aliasPrefix) }
            .map { column -> statement.mappingColumn(dynamicField, column) }
        val mappingType = AnnotationConstants.MappingType.fromString(dynamicField.annotations.mappingType)
        val rawPropertyType = dynamicField.annotations.propertyType
            ?: error("Dynamic field '${dynamicField.src.fieldName}' is missing propertyType.")
        val propertyType = rawPropertyType.toDartTypeName().removeSuffix("?")
        val className = if (mappingType == AnnotationConstants.MappingType.COLLECTION) {
            rawPropertyType.collectionElementType()
        } else {
            propertyType
        }
        val constructor = buildString {
            append("$className(")
            columns.forEach { column ->
                val value = if (fromJoinedRow) {
                    "$rowVar.${column.sourcePropertyName}${if (column.field.nullable) "" else "!"}"
                } else {
                    readFieldExpression(null, column.field, rowVar, fromJoinedRow = false)
                }
                append("${column.constructorPropertyName}: $value, ")
            }
            append(")")
        }
        val nullable = dynamicField.annotations.notNull != true &&
            mappingType != AnnotationConstants.MappingType.ENTITY
        if (!nullable) return constructor
        val nullCheck = columns.joinToString(" && ") { column ->
            if (fromJoinedRow) {
                "$rowVar.${column.sourcePropertyName} == null"
            } else {
                "$rowVar.readValue(${column.field.index}) == null"
            }
        }
        return "($nullCheck ? null : $constructor)"
    }

    private fun parameterListExpression(params: List<DartParameter>): String {
        return buildString {
            append("[")
            params.forEach { param ->
                val rawValue = "params.${param.propertyName}"
                val value = when {
                    param.adapter == null -> rawValue
                    param.dartType.removeSuffix("?").startsWith("List<") -> {
                        val mapped = "$rawValue.map((value) => _db.adapters.${param.adapter.encodeName}(value)).toList()"
                        if (param.dartType.endsWith("?")) {
                            "$rawValue?.map((value) => _db.adapters.${param.adapter.encodeName}(value)).toList()"
                        } else {
                            mapped
                        }
                    }

                    else -> "_db.adapters.${param.adapter.encodeName}($rawValue)"
                }
                append("$value, ")
            }
            append("]")
        }
    }

    private fun collectAdapters() {
        context.createTableStatements.forEach { table ->
            table.columns.forEach { column ->
                if (!column.hasAdapter()) return@forEach
                adapterFor(table.src.tableName, column.src.name, column)
            }
        }
    }

    private fun parameterDescriptors(statement: AnnotatedStatement, unique: Boolean): List<DartParameter> {
        val names = if (unique) {
            statement.srcNamedParameters().distinct()
        } else {
            statement.srcNamedParameters()
        }
        return names.map { name ->
            val propertyName = statement.annotations.propertyNameGenerator.convertToPropertyName(name)
            val type = dataStructCodeGenerator.inferParameterType(name, statement).toDartType()
            val column = parameterColumn(statement, name)
            DartParameter(
                propertyName = propertyName,
                dartType = type,
                adapter = column?.let { adapterFor(it.first.src.tableName, it.second.src.name, it.second) },
            )
        }
    }

    private fun parameterColumn(
        statement: AnnotatedStatement,
        parameterName: String,
    ): Pair<AnnotatedCreateTableStatement, AnnotatedCreateTableStatement.Column>? {
        val tableAndColumn = when (statement) {
            is AnnotatedExecuteStatement -> when (val src = statement.src) {
                is InsertStatement -> src.table to src.columnNamesAssociatedWithNamedParameters[parameterName]
                is UpdateStatement -> src.table to src.namedParametersToColumnNames[parameterName]
                is DeleteStatement -> src.table to null
            }

            is AnnotatedSelectStatement -> {
                val column = context.columnLookup.findColumnForParameter(statement, parameterName)
                    ?: return null
                return context.createTableStatements
                    .firstOrNull { it.findColumnByName(column.src.name) === column }
                    ?.let { it to column }
            }

            else -> return null
        }
        val tableName = tableAndColumn.first
        val columnName = tableAndColumn.second ?: return null
        val table = context.createTableStatements.firstOrNull {
            it.src.tableName.equals(tableName, ignoreCase = true)
        } ?: return null
        val column = table.findColumnByName(columnName) ?: return null
        return table to column
    }

    private fun selectStatements(): List<Pair<String, AnnotatedSelectStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.filterIsInstance<AnnotatedSelectStatement>().map { namespace to it }
        }

    private fun executeStatements(): List<Pair<String, AnnotatedExecuteStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.filterIsInstance<AnnotatedExecuteStatement>().map { namespace to it }
        }

    private fun statements(): List<Pair<String, AnnotatedStatement>> =
        context.nsWithStatements.flatMap { (namespace, statements) ->
            statements.mapNotNull { statement ->
                when (statement) {
                    is AnnotatedSelectStatement,
                    is AnnotatedExecuteStatement -> namespace to statement

                    else -> null
                }
            }
        }

    private fun namespaces(): List<String> = context.nsWithStatements.keys.sorted()

    private fun usesUint8List(): Boolean {
        return context.createTableStatements.any { table ->
            table.columns.any { it.toDartType().removeSuffix("?") == "Uint8List" }
        } || selectStatements().any { (_, statement) ->
            statement.fields().any { it.dartType.removeSuffix("?") == "Uint8List" }
        } || executeStatements().any { (_, statement) ->
            statement.hasReturningClause() &&
                returningFields(statement).any { it.dartType.removeSuffix("?") == "Uint8List" }
        }
    }

    private fun adapterConstructorParameter(): String =
        if (adapterColumns.isEmpty()) {
            "${databaseName}Adapters adapters = const ${databaseName}Adapters(),"
        } else {
            "required ${databaseName}Adapters adapters,"
        }

    private fun selectResultClassName(namespace: String, statement: AnnotatedSelectStatement): String =
        statement.annotations.queryResult ?: "${pascalize(namespace)}${statement.getDataClassName()}Result"

    private fun joinedResultClassName(namespace: String, statement: AnnotatedSelectStatement): String =
        "_${selectResultClassName(namespace, statement)}JoinedRow"

    private fun returningResultClassName(namespace: String, statement: AnnotatedExecuteStatement): String =
        statement.annotations.queryResult ?: "${pascalize(namespace)}${statement.getDataClassName()}Result"

    private fun paramsClassName(namespace: String, statement: AnnotatedStatement): String =
        "${pascalize(namespace)}${statement.getDataClassName()}Params"

    private fun AnnotatedSelectStatement.fields(): List<DartField> =
        mappingPlan.regularFields.map { field ->
            toDartField(field)
        } + mappingPlan.includedDynamicFields.map { field ->
            val propertyType = field.annotations.propertyType
                ?: error("Dynamic field '${field.src.fieldName}' is missing propertyType.")
            val mappingType = field.annotations.mappingType?.let { AnnotationConstants.MappingType.fromString(it) }
            DartField(
                index = -1,
                propertyName = dynamicFieldPropertyName(field),
                dartType = propertyType.toDartTypeName().let { type ->
                    if (mappingType == AnnotationConstants.MappingType.COLLECTION || field.annotations.notNull == true) {
                        type.removeSuffix("?")
                    } else {
                        type.withNullable(true)
                    }
                },
                sqliteReadCall = "",
                nullable = field.annotations.notNull != true,
                adapter = null,
                source = field,
                dynamicField = field,
            )
        }

    private fun AnnotatedSelectStatement.physicalFields(): List<DartField> =
        fields.filterNot { it.annotations.isDynamicField }.map { field ->
            toDartField(field)
        }

    private fun AnnotatedSelectStatement.toDartField(field: AnnotatedSelectStatement.Field): DartField {
        val propertyName = field.annotations.propertyName
            ?: annotations.propertyNameGenerator.convertToPropertyName(field.src.fieldName)
        val table = createTableForSelectField(this, field.src)
        val column = table?.findColumnByName(field.src.originalColumnName)
        val adapter = column?.let { adapterFor(table.src.tableName, it.src.name, it) }
        return DartField(
            index = physicalFieldIndex(field.src),
            propertyName = propertyName,
            dartType = field.toDartType(),
            sqliteReadCall = field.src.dataType.sqliteReadCall(nullable = field.isNullable()),
            nullable = field.isNullable(),
            adapter = adapter,
            source = field,
            dynamicField = null,
        )
    }

    private fun AnnotatedSelectStatement.mappingColumn(
        dynamicField: AnnotatedSelectStatement.Field,
        column: SelectStatement.FieldSource,
    ): DartMappingColumn {
        val field = fields.firstOrNull { !it.annotations.isDynamicField && it.src.fieldName == column.fieldName }
            ?: error("Mapped column '${column.fieldName}' not found in Dart SELECT '${name}'.")
        val physical = toDartField(field)
        val aliasPrefix = dynamicField.annotations.aliasPrefix
        val rawName = if (!aliasPrefix.isNullOrBlank() && column.fieldName.startsWith(aliasPrefix)) {
            column.fieldName.removePrefix(aliasPrefix)
        } else {
            column.fieldName
        }.substringBefore(":")
        val tableColumn = createTableForSelectField(this, column)
            ?.findColumnByName(column.originalColumnName)
        val tablePropertyName = tableColumn
            ?.parsedFieldAnnotations()
            ?.propertyName
        val constructorField = tableColumn?.let { resolvedColumn ->
            val adapter = adapterFor(
                tableName = createTableForSelectField(this, column)!!.src.tableName,
                columnName = resolvedColumn.src.name,
                column = resolvedColumn,
            )
            physical.copy(
                dartType = resolvedColumn.toDartType(),
                sqliteReadCall = resolvedColumn.src.dataType.sqliteReadCall(nullable = resolvedColumn.isNullable()),
                nullable = resolvedColumn.isNullable(),
                adapter = adapter,
            )
        } ?: if (dynamicField.annotations.notNull == true) {
            physical.copy(
                dartType = physical.dartType.removeSuffix("?"),
                sqliteReadCall = column.dataType.sqliteReadCall(nullable = false),
                nullable = false,
            )
        } else {
            physical
        }
        return DartMappingColumn(
            sourcePropertyName = physical.propertyName,
            constructorPropertyName = tablePropertyName ?: annotations.propertyNameGenerator.convertToPropertyName(rawName),
            field = constructorField,
        )
    }

    private fun AnnotatedSelectStatement.physicalFieldIndex(column: SelectStatement.FieldSource): Int =
        src.fields.indexOfFirst { it.fieldName == column.fieldName }.takeIf { it >= 0 }
            ?: error("Column '${column.fieldName}' not found in SELECT '${name}'.")

    private fun createTableForSelectField(
        statement: AnnotatedSelectStatement,
        field: SelectStatement.FieldSource,
    ): AnnotatedCreateTableStatement? {
        val tableName = statement.src.tableAliases[field.tableName] ?: field.tableName
        return context.createTableStatements.firstOrNull {
            it.src.tableName.equals(tableName, ignoreCase = true)
        }
    }

    private fun dynamicFieldPropertyName(field: AnnotatedSelectStatement.Field): String =
        field.annotations.propertyName ?: field.src.fieldName

    private fun returningFields(statement: AnnotatedExecuteStatement): List<DartField> {
        val table = context.createTableStatements.first {
            it.src.tableName.equals(statement.src.table, ignoreCase = true)
        }
        return statement.getReturningColumns().mapIndexed { index, columnName ->
            val column = table.findColumnByName(columnName)
                ?: error("RETURNING column '$columnName' not found on table '${table.src.tableName}'.")
            val propertyName = statement.annotations.propertyNameGenerator.convertToPropertyName(column.src.name)
            val adapter = adapterFor(table.src.tableName, column.src.name, column)
            DartField(
                index = index,
                propertyName = propertyName,
                dartType = column.toDartType(),
                sqliteReadCall = column.src.dataType.sqliteReadCall(nullable = column.isNullable()),
                nullable = column.isNullable(),
                adapter = adapter,
            )
        }
    }

    private fun AnnotatedSelectStatement.Field.toDartType(): String {
        val explicit = annotations.propertyType?.toDartTypeName()
        if (explicit != null) return explicit.withNullable(isNullable())
        return src.dataType.sqliteDartType().withNullable(isNullable())
    }

    private fun AnnotatedCreateTableStatement.Column.toDartType(): String {
        val explicit = parsedFieldAnnotations().propertyType?.toDartTypeName()
        if (explicit != null) return explicit.withNullable(isNullable())
        return src.dataType.sqliteDartType().withNullable(isNullable())
    }

    private fun AnnotatedSelectStatement.Field.isNullable(): Boolean {
        annotations.notNull?.let { return !it }
        return src.isNullable
    }

    private fun adapterFor(
        tableName: String,
        columnName: String,
        column: AnnotatedCreateTableStatement.Column,
    ): DartAdapterColumn? {
        if (!column.hasAdapter()) return null
        val key = "${tableName.lowercase(Locale.ROOT)}.${columnName.lowercase(Locale.ROOT)}"
        return adapterColumns.getOrPut(key) {
            val baseName = "${pascalize(tableName)}${pascalize(columnName)}"
            DartAdapterColumn(
                encodeName = "${baseName.replaceFirstChar { it.lowercase() }}ToSql",
                decodeName = "sqlValueTo$baseName",
            )
        }
    }

    private fun affectedTables(statement: AnnotatedStatement): Set<String> {
        fun expandTables(tables: Set<String>): Set<String> {
            val expanded = mutableSetOf<String>()
            tables.forEach { table ->
                val key = table.lowercase(Locale.ROOT)
                expanded += key
                viewTableDependencies[key]?.let { expanded += it }
            }
            return expanded
        }

        return when (statement) {
            is AnnotatedSelectStatement -> buildSet {
                statement.src.fromTable?.let { add(it) }
                statement.src.joinTables.forEach { add(it) }
            }.let(::expandTables)

            is AnnotatedExecuteStatement -> {
                val cascadeTables = when (statement.src) {
                    is InsertStatement -> cascadeTablesFor(
                        statement.src.table,
                        StatementAnnotationOverrides.CascadeAction.INSERT
                    )

                    is UpdateStatement -> cascadeTablesFor(
                        statement.src.table,
                        StatementAnnotationOverrides.CascadeAction.UPDATE
                    )

                    is DeleteStatement -> cascadeTablesFor(
                        statement.src.table,
                        StatementAnnotationOverrides.CascadeAction.DELETE
                    )
                }
                expandTables(setOf(statement.src.table) + cascadeTables)
            }

            else -> emptySet()
        }
    }

    private fun migrationSteps(): List<DartMigrationStep> {
        if (migrationInspector.sqlStatements.isNotEmpty()) {
            val bootstrapStatements =
                schemaInspector.sqlStatements.map { it.sql } + sqlBatchInspector.sqlStatements.map { it.sql }
            return buildList {
                if (bootstrapStatements.isNotEmpty()) {
                    add(DartMigrationStep(migrationInspector.latestVersion, bootstrapStatements, freshOnly = true))
                }
                migrationInspector.sqlStatements.forEach { (version, statements) ->
                    add(DartMigrationStep(version, statements.map { it.sql }))
                }
            }
        }
        val statements = schemaInspector.sqlStatements.map { it.sql } + sqlBatchInspector.sqlStatements.map { it.sql }
        return if (statements.isEmpty()) {
            emptyList()
        } else {
            listOf(DartMigrationStep(1, statements))
        }
    }

    private fun resolveViewDependencies(
        viewName: String,
        seen: MutableSet<String>,
    ): Set<String> {
        if (!seen.add(viewName)) return emptySet()
        val view = createViewStatementsByName[viewName] ?: return emptySet()
        val dependencies = mutableSetOf<String>()
        val select = view.src.selectStatement
        val referencedTables = buildList {
            select.fromTable?.let { add(it) }
            addAll(select.joinTables)
        }
        referencedTables.forEach { table ->
            val key = table.lowercase(Locale.ROOT)
            dependencies += key
            dependencies += resolveViewDependencies(key, seen)
        }
        return dependencies
    }

    private fun cascadeTablesFor(
        tableName: String,
        action: StatementAnnotationOverrides.CascadeAction,
    ): Set<String> {
        val lowercase = tableName.lowercase(Locale.ROOT)
        val cacheKey = lowercase to action
        cascadeClosureCache[cacheKey]?.let { return it }

        val closure = computeCascadeClosure(
            startTable = lowercase,
            action = action,
            visited = mutableSetOf()
        )
        cascadeClosureCache[cacheKey] = closure
        return closure
    }

    private fun computeCascadeClosure(
        startTable: String,
        action: StatementAnnotationOverrides.CascadeAction,
        visited: MutableSet<String>,
    ): Set<String> {
        if (!visited.add(startTable)) return emptySet()
        val direct = cascadeNotifyByTable[startTable]?.tablesFor(action) ?: emptySet()
        if (direct.isEmpty()) return emptySet()

        val result = mutableSetOf<String>()
        direct.forEach { childRaw ->
            val child = childRaw.lowercase(Locale.ROOT)
            if (result.add(child)) {
                result += computeCascadeClosure(child, action, visited)
            }
        }
        return result
    }

    private fun AnnotatedStatement.srcNamedParameters(): List<String> =
        when (this) {
            is AnnotatedSelectStatement -> src.namedParameters
            is AnnotatedExecuteStatement -> src.namedParameters
            else -> emptyList()
        }

    private fun TypeName.toDartType(): String {
        val nullable = toString().endsWith("?")
        val rawType = toString().removeSuffix("?")
        val type = rawType.removePrefix("kotlin.")
        val dartType = when {
            type == "Int" || type == "Long" || type == "Short" || type == "Byte" -> "int"
            type == "Double" || type == "Float" -> "double"
            type == "Boolean" -> "bool"
            type == "String" -> "String"
            type == "ByteArray" -> "Uint8List"
            rawType.startsWith("kotlin.collections.Collection<") -> "List<${rawType.substringAfter("<").substringBeforeLast(">").toDartTypeName()}>"
            rawType.startsWith("kotlin.collections.List<") -> "List<${rawType.substringAfter("<").substringBeforeLast(">").toDartTypeName()}>"
            else -> type.toDartTypeName()
        }
        return dartType.withNullable(nullable)
    }

    private fun String.sqliteDartType(): String {
        val normalized = uppercase(Locale.ROOT)
        return when {
            "INT" in normalized -> "int"
            "REAL" in normalized || "FLOA" in normalized || "DOUB" in normalized -> "double"
            "BLOB" in normalized -> "Uint8List"
            else -> "String"
        }
    }

    private fun String.sqliteReadCall(nullable: Boolean): String {
        val prefix = if (nullable) "readNullable" else "read"
        val normalized = uppercase(Locale.ROOT)
        return when {
            "INT" in normalized -> "${prefix}Int"
            "REAL" in normalized || "FLOA" in normalized || "DOUB" in normalized -> "${prefix}Double"
            "BLOB" in normalized -> "${prefix}Blob"
            else -> "${prefix}String"
        }
    }

    private fun String.toDartTypeName(): String {
        val trimmed = removePrefix("kotlin.").removePrefix("dart.").substringAfterLast('.')
        return when (trimmed) {
            "Int", "Long", "Short", "Byte" -> "int"
            "Double", "Float" -> "double"
            "Boolean" -> "bool"
            "String" -> "String"
            "ByteArray" -> "Uint8List"
            else -> trimmed
        }
    }

    private fun String.collectionElementType(): String {
        val type = toDartTypeName().removeSuffix("?")
        require(type.startsWith("List<") && type.endsWith(">")) {
            "Expected Dart collection type, got '$this'."
        }
        return type.removePrefix("List<").removeSuffix(">")
    }

    private fun String.withNullable(nullable: Boolean): String =
        if (nullable && !endsWith("?")) "$this?" else this
}

private data class DartField(
    val index: Int,
    val propertyName: String,
    val dartType: String,
    val sqliteReadCall: String,
    val nullable: Boolean,
    val adapter: DartAdapterColumn?,
    val source: AnnotatedSelectStatement.Field? = null,
    val dynamicField: AnnotatedSelectStatement.Field? = null,
)

private data class DartMappingColumn(
    val sourcePropertyName: String,
    val constructorPropertyName: String,
    val field: DartField,
)

private data class DartParameter(
    val propertyName: String,
    val dartType: String,
    val adapter: DartAdapterColumn?,
)

private data class DartAdapterColumn(
    val encodeName: String,
    val decodeName: String,
)

private data class DartMigrationStep(
    val version: Int,
    val statements: List<String>,
    val freshOnly: Boolean = false,
)

private fun AnnotatedCreateTableStatement.Column.parsedFieldAnnotations(): FieldAnnotationOverrides =
    FieldAnnotationOverrides.parse(annotations)

private fun AnnotatedCreateTableStatement.Column.hasAdapter(): Boolean =
    parsedFieldAnnotations().adapter == true

private class DartWriter {
    private val builder = StringBuilder()
    private var indentLevel = 0

    fun line(value: String = "") {
        if (value.isNotEmpty()) {
            repeat(indentLevel) { builder.append("  ") }
        }
        builder.append(value).append('\n')
    }

    fun indent(block: DartWriter.() -> Unit) {
        indentLevel++
        block()
        indentLevel--
    }

    override fun toString(): String = builder.toString().trimEnd() + "\n"
}

private fun String.toLowerCamel(): String {
    val pascal = pascalize(this)
    return pascal.replaceFirstChar { it.lowercase() }
}

private fun String.toSnakeCase(): String {
    val out = StringBuilder()
    forEachIndexed { index, char ->
        if (char.isUpperCase() && index > 0) {
            out.append('_')
        }
        out.append(char.lowercaseChar())
    }
    return out.toString()
}

private fun String.toDartRawString(): String {
    require(!contains("'''")) {
        "Dart raw string emitter does not support SQL containing triple single quotes yet."
    }
    return "r'''$this'''"
}

private fun Set<String>.toDartSetLiteral(): String =
    if (isEmpty()) {
        "const <String>{}"
    } else {
        "const <String>{${joinToString(", ") { "'$it'" }}}"
    }

private fun List<DartParameter>.forwardingArgument(): String =
    if (isEmpty()) "" else "params"
