INSERT INTO person(id,
                   email,
                   first_name,
                   last_name,
                   phone,
                   birth_date,
                   ssn,
                   score,
                   is_active,
                   notes)
VALUES (:id,
        :email,
        :firstName,
        :lastName,
        :phone,
        :birthDate,
        :ssn,
        :score,
        :isActive,
        :notes)
ON CONFLICT(email) DO UPDATE SET first_name = :firstName,
                                 last_name  = :lastName,
                                 phone      = :phone,
                                 birth_date = :birthDate,
                                 ssn        = :ssn,
                                 score      = :score,
                                 is_active  = :isActive,
                                 notes      = :notes;
