CREATE TABLE users (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  parent_id TEXT REFERENCES categories(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE teams (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  captain_member_id TEXT REFERENCES team_members(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE team_members (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE files (
  id BLOB PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  data BLOB NOT NULL
);

CREATE TABLE file_reviews (
  id BLOB PRIMARY KEY NOT NULL,
  review TEXT NOT NULL,
  file_id BLOB NOT NULL REFERENCES files(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE typed_rows (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  note TEXT NULL,
  count_value INTEGER NULL,
  small_count INTEGER NULL,
  medium_count INTEGER NULL,
  exact_amount TEXT NULL,
  enabled_flag INTEGER NOT NULL,
  rating REAL NULL,
  float4_value REAL NULL,
  data BLOB NULL,
  created_at TEXT NULL
);
