name: sqlitenow_flutter_todo
description: Flutter example for SQLiteNow Dart generation.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  sqlitenow_runtime: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqlite3: ^3.3.1
  sqlitenow_cli: ^0.10.0
  sqlitenow_oversqlite: ^0.10.0

dependency_overrides:
  sqlitenow_runtime:
    path: ../../packages/sqlitenow_runtime
  sqlitenow_cli:
    path: ../../packages/sqlitenow_cli
  sqlitenow_oversqlite:
    path: ../../packages/sqlitenow_oversqlite

flutter:
  uses-material-design: true
